package com.JoaoMoraes.Modelos;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORCAMENTO.
 */
public class Orcamento {

    private Long id;
    private Long IEvendedor;
    private Long IEcliente;
    private Long IEprazo;
    private String Numero;
    private Byte Situacao;
    private java.util.Date DataEmissao;
    private Double ValorFlutuante;
    private Double AliquotaFlutuante;
    private Byte FluxoFlutuante;
    private Double ValorContabil;
    private Double ValorTotal;
    private Byte SituacaoEnvio;
    private java.util.Date DataEnvio;
    private java.util.Date DataEdicao;

    public Orcamento() {
    }

    public Orcamento(Long id) {
        this.id = id;
    }

    public Orcamento(Long id, Long IEvendedor, Long IEcliente, Long IEprazo, String Numero, Byte Situacao, java.util.Date DataEmissao, Double ValorFlutuante, Double AliquotaFlutuante, Byte FluxoFlutuante, Double ValorContabil, Double ValorTotal, Byte SituacaoEnvio, java.util.Date DataEnvio, java.util.Date DataEdicao) {
        this.id = id;
        this.IEvendedor = IEvendedor;
        this.IEcliente = IEcliente;
        this.IEprazo = IEprazo;
        this.Numero = Numero;
        this.Situacao = Situacao;
        this.DataEmissao = DataEmissao;
        this.ValorFlutuante = ValorFlutuante;
        this.AliquotaFlutuante = AliquotaFlutuante;
        this.FluxoFlutuante = FluxoFlutuante;
        this.ValorContabil = ValorContabil;
        this.ValorTotal = ValorTotal;
        this.SituacaoEnvio = SituacaoEnvio;
        this.DataEnvio = DataEnvio;
        this.DataEdicao = DataEdicao;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIEvendedor() {
        return IEvendedor;
    }

    public void setIEvendedor(Long IEvendedor) {
        this.IEvendedor = IEvendedor;
    }

    public Long getIEcliente() {
        return IEcliente;
    }

    public void setIEcliente(Long IEcliente) {
        this.IEcliente = IEcliente;
    }

    public Long getIEprazo() {
        return IEprazo;
    }

    public void setIEprazo(Long IEprazo) {
        this.IEprazo = IEprazo;
    }

    public String getNumero() {
        return Numero;
    }

    public void setNumero(String Numero) {
        this.Numero = Numero;
    }

    public Byte getSituacao() {
        return Situacao;
    }

    public void setSituacao(Byte Situacao) {
        this.Situacao = Situacao;
    }

    public java.util.Date getDataEmissao() {
        return DataEmissao;
    }

    public void setDataEmissao(java.util.Date DataEmissao) {
        this.DataEmissao = DataEmissao;
    }

    public Double getValorFlutuante() {
        return ValorFlutuante;
    }

    public void setValorFlutuante(Double ValorFlutuante) {
        this.ValorFlutuante = ValorFlutuante;
    }

    public Double getAliquotaFlutuante() {
        return AliquotaFlutuante;
    }

    public void setAliquotaFlutuante(Double AliquotaFlutuante) {
        this.AliquotaFlutuante = AliquotaFlutuante;
    }

    public Byte getFluxoFlutuante() {
        return FluxoFlutuante;
    }

    public void setFluxoFlutuante(Byte FluxoFlutuante) {
        this.FluxoFlutuante = FluxoFlutuante;
    }

    public Double getValorContabil() {
        return ValorContabil;
    }

    public void setValorContabil(Double ValorContabil) {
        this.ValorContabil = ValorContabil;
    }

    public Double getValorTotal() {
        return ValorTotal;
    }

    public void setValorTotal(Double ValorTotal) {
        this.ValorTotal = ValorTotal;
    }

    public Byte getSituacaoEnvio() {
        return SituacaoEnvio;
    }

    public void setSituacaoEnvio(Byte SituacaoEnvio) {
        this.SituacaoEnvio = SituacaoEnvio;
    }

    public java.util.Date getDataEnvio() {
        return DataEnvio;
    }

    public void setDataEnvio(java.util.Date DataEnvio) {
        this.DataEnvio = DataEnvio;
    }

    public java.util.Date getDataEdicao() {
        return DataEdicao;
    }

    public void setDataEdicao(java.util.Date DataEdicao) {
        this.DataEdicao = DataEdicao;
    }

}
